name: Build Flutter Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
#  build:
#    runs-on: macos-latest
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Set up Flutter
#        uses: subosito/flutter-action@v2
#        with:
#          flutter-version: '3.x'
#
#      - name: Install dependencies
#        run: flutter pub get
#
#      - name: Build APK
#        run: flutter build apk --debug
#
#      - name: Upload APK artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: app-debug-apk
#          path: build/app/outputs/flutter-apk/app-debug.apk

  maestro-test:
#    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Download APK artifact
#        uses: actions/download-artifact@v4
#        with:
#          name: app-debug-apk
#          path: ./apk

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install ADB
        run: sudo apt-get update && sudo apt-get install -y android-tools-adb

      - name: Install Maestro CLI
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Start Android Emulator
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          profile: pixel
          force-avd-creation: true
          emulator-options: -no-window -no-audio -no-boot-anim
          script: adb install ./apk/app-debug.apk; maestro test maestro/counter_test.yaml
